create table role_table
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
insert into role_table (id, name)
values (1, 'ROLE_USER');
insert into role_table (id, name)
values (2, 'ROLE_ADMIN');

